### ISSUE TITLE
Issue #01

### ISSUE THREAD

**Issue by MsMedicMain** [zoogie/Frogtool#3]
Tried using the standard os on my pc to compile it (windows)... realized I had to use Linux. (please have the release in a zip file for older versions) (sorry if this made ur life more difficult, that was unintentional) thanks. Sorry for wasting ur time.

**Comment by zoogie** [comment]
https://cdn.discordapp.com/attachments/441119928334942218/518318446765801475/Frogtool_old_binaries.zip

**Comment by MsMedicMain** [comment]
Thank you, sorry for the trouble.
