### ISSUE TITLE
about frogtool for 3ds

### ISSUE THREAD

**Issue by Porthin** [zoogie/Frogtool#4]
the frogtool v1.1 used to have a folder called privet
the new frogtool v2.1RC dous not have this folder and frogtool v1.1 or aka (RELEASE.zip) aka (more frog edtion) is nowhere to be found in your profile plz help can i do it with out a privet folder?

**Comment by zoogie** [comment]
It's built in and copied automatically.
https://github.com/zoogie/Frogtool/blob/5cc06bfa8fef9a84bc86933f5dc0e05332465a62/source/main.cpp#L272
