### ISSUE TITLE
Frogtool v1.1 3dsx file

### ISSUE THREAD

**Issue by Soupalaseg** [zoogie/Frogtool#5]
Hello, 

is it possible to have download frogtool v1.1 3dsx file?
Main guides aren't up to date to use your last version.
Regards.
Soupalaseg

**Comment by Soupalaseg** [comment]
Found : https://cdn.discordapp.com/attachments/441119928334942218/518318446765801475/Frogtool_old_binaries.zip

**Comment by jason0597** [comment]
[Frogtool_old_binaries.zip](https://github.com/zoogie/Frogtool/files/2857946/Frogtool_old_binaries.zip)
Here's a GitHub mirror in case the discord link goes down, you never know with those things.
